---
title: "Tutorial: Instrumental Variable Method"
format:
  pdf:
    geometry:
    - paperwidth=8.5in
    - paperheight=11in
    - margin=1in
    toc: false
    number-sections: true
    colorlinks: true
---

```{=latex}
\vspace{-2.5cm}
```
# Overview

This tutorial introduces **instrumental variable methods** by replicating some of the key results in the paper:

Acemoglu, Daron, Simon Johnson, and James A. Robinson. 2001. "The Colonial Origins of Comparative Development: An Empirical Investigation." American Economic Review 91 (5): 1369–1401. [[link]](https://www.aeaweb.org/articles?id=10.1257/aer.91.5.1369) [AJR]

## Learning Objectives

By the end of this tutorial, you should:

- have a good understanding of the main assumptions underlying instrumental variable method
- be able to estimate IV model from scratch
- compare IV estimates with OLS
- conduct robustness checks to ensure your model is valid

## Pre-requisites

You must attempt this exercise prior to your tutorial. To make the most out of this session, you should:

- Download the relevant files (data and R script)
- Read the introduction section of the paper
- Run the R script and understand each step

# Task

1. Read the introduction of the AJR paper and answer the following questions:
   (a) Briefly discuss the main insight from the paper.
   (b) Estimate the following equation using OLS:
   $$
  \log y_{i} = \mu + \alpha R_{i} + \mathbf{X}'_{i}\gamma + u_{i}
  $$
  where,
    - $y_{i}$ is income per capita (`logpgp95`)
    - $R_{i}$ protection against expropriation measure (`avexpr`)
    - $\mathbf{X}_i$ vector of other variables (`lat_abst`, `f_brit`, `f_french`, `sjlofr`, `catho80`, `muslim80` and `no_cpm80`)
    - $u_{i}$ is random error.
   (c) Can we rely on the ols estimate $\hat{\alpha}$ in (b)? Briefly explain.
   (d) Estimate the above equation by TSLS using log settler mortality (`logem4`) as an instrument for $R_{i}$ (`avexpr`).
   (e) Test for relevance of `logem4` as an instrument for `avexpr` using F-test and the robust Anderson-Rubin test.
   (f) Does `logem4` satisfy instrument exogeneity? Discuss.